version: '3'

services:
  l1_memory_cache:
    container_name: l1_memory_cache
    build: 
      context: ./l1-memory-cache
      dockerfile: DockerFile
    volumes: 
      - ./l1-memory-cache:/app
    ports: 
      - 9090:80